#!/bin/bash

function main() {
    declare -i retry=retry+1
    echo "Retry time: $retry"
    khh-server main && exit || sleep 10m && main
}

cd ~/projects/kanhan-helper
source .env/bin/activate
retry=0
main
