#!/bin/bash

cd ~/projects/kanhan-helper
source .env/bin/activate
retry=0

for (( i=1; i<10; i++ ))
do
    khh-server main && exit
    declare -i retry=retry+1
    echo "Retry time: $retry"
    sleep 10m
done
